NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.general.uae.com-8054-GeneralCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.general.uae.com-8054-GeneralCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.general.uae.com-8054-GeneralCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.general.uae.com-8054-GeneralCA.pem
    OrganizationalUnitIdentifier: orderer
