NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.government.uae.com-7054-GovernmentCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.government.uae.com-7054-GovernmentCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.government.uae.com-7054-GovernmentCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.government.uae.com-7054-GovernmentCA.pem
    OrganizationalUnitIdentifier: orderer
